name: Enable Automerge
on:
  pull_request_target:
    types:
      - reopened
      - labeled

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    if: github.event.pull_request.user.login == 'mschuwalow' && contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
    - uses: alexwilson/enable-github-automerge-action@1.0.0
      with:
        github-token: "${{ secrets.GH_TOKEN }}"
